services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
      - ./nginx/www/:/var/www/:rw
    networks:
      - internal
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
      - MONGODB_PROJECT_PASSWORD=${MONGODB_PROJECT_PASSWORD}
      - MONGODB_PROJECT_USERNAME=${MONGODB_PROJECT_USERNAME}
    volumes:
      - ./mongo/data:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    networks:
      - internal
  api:
    build: https://github.com/chuchorv4/api-ayuntamientos2024.git
    restart: always
    environment:
      - MONGODB_USER=${MONGODB_PROJECT_USERNAME}
      - MONGODB_PASS=${MONGODB_PROJECT_PASSWORD}
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DB=ayuntamientos
    networks:
      - internal
networks:
  internal:
    driver: bridge